import { useState, useEffect } from 'react';
import { Printer } from 'lucide-react';
import { investigationService } from '../../services/investigationService';
import { timelineService } from '../../services/timelineService';
import { reconstructionService } from '../../services/reconstructionService';
import { impactService } from '../../services/impactService';
import { rarfService } from '../../services/rarfService';
import { evidenceService } from '../../services/evidenceService';

import { ReportSection } from '../../components/report/ReportSection';
import { ExecutiveSummary } from '../../components/report/ExecutiveSummary';
import { Timeline } from '../../components/timeline/Timeline';
import { AttackStageCard } from '../../components/reconstruction/AttackStage';
import { ImpactScore } from '../../components/impact/ImpactScore';
import { ImpactCategoryCard } from '../../components/impact/ImpactCategoryCard';
import { EvidenceList } from '../../components/evidence/EvidenceList';
import { RARFViewer } from '../../components/rarf/RARFViewer';
import { Button } from '../../components/ui/Button';

export default function ReportTab({ investigationId }: { investigationId: string }) {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchAll() {
      setLoading(true);
      const [
        inv,
        timeline,
        reconstruction,
        impact,
        rarf,
        evidence
      ] = await Promise.all([
        investigationService.getInvestigation(investigationId),
        timelineService.getTimelineForInvestigation(investigationId),
        reconstructionService.getReconstructionSession(investigationId),
        impactService.getImpactForInvestigation(investigationId),
        rarfService.getRARFDocument(investigationId),
        evidenceService.getEvidenceForInvestigation(investigationId)
      ]);

      setData({ inv, timeline, reconstruction, impact, rarf, evidence });
      setLoading(false);
    }
    fetchAll();
  }, [investigationId]);

  if (loading) {
    return (
      <div className="animate-pulse space-y-8 max-w-5xl">
        <div className="h-40 bg-raven-bg-surface-2 rounded-lg" />
        <div className="h-64 bg-raven-bg-surface-2 rounded-lg" />
        <div className="h-64 bg-raven-bg-surface-2 rounded-lg" />
      </div>
    );
  }

  if (!data || !data.inv) return <div>Failed to load report data.</div>;

  return (
    <div className="max-w-5xl bg-raven-bg-base text-raven-text-primary pb-20">
      
      {/* Report Controls (Hidden in Print) */}
      <div className="flex justify-end mb-6 print:hidden">
        <Button variant="secondary" onClick={() => window.print()}>
          <Printer size={16} className="mr-2" />
          Print Report
        </Button>
      </div>

      <div className="bg-raven-bg-surface p-8 md:p-12 rounded-lg border border-raven-border-subtle shadow-lg print:border-none print:shadow-none print:bg-white print:text-black">
        
        {/* Document Header */}
        <div className="text-center mb-12 border-b border-raven-border-subtle pb-8">
          <h1 className="text-3xl font-black uppercase tracking-tight mb-2">Investigation Report</h1>
          <p className="text-raven-text-secondary">Generated by RAVEN Intelligence System</p>
        </div>

        {/* 1. Executive Summary */}
        <ReportSection title="1. Executive Summary">
          <ExecutiveSummary 
            investigation={data.inv} 
            summaryText={data.reconstruction?.summary || data.inv.title} 
          />
        </ReportSection>

        {/* 2. What Happened? */}
        <ReportSection title="2. What Happened?">
          <p className="leading-relaxed">
            Based on the correlated evidence, a highly privileged service account was compromised and utilized to deploy ransomware across the network. The incident resulted in the encryption of core file shares and required active intervention to contain outbound C2 beaconing.
          </p>
        </ReportSection>

        {/* 3. How Did It Happen? */}
        <ReportSection title="3. How Did It Happen?">
          <p className="leading-relaxed">
            Initial access vector remains unconfirmed, but evidence strongly points to credential theft or an exposed RDP session. Following initial access, the actor utilized legitimate administrative tools (`vssadmin.exe`) to disable recovery options before executing the primary encryption payload via batch scripts in temporary directories.
          </p>
        </ReportSection>

        {/* 4. Attack Timeline */}
        <ReportSection title="4. Attack Timeline">
          {data.timeline?.length > 0 ? (
            <Timeline events={data.timeline} />
          ) : (
            <p className="italic text-raven-text-tertiary">No timeline events recorded.</p>
          )}
        </ReportSection>

        {/* 5. Detection Evidence (Using EvidenceList as a proxy for raw alerts) */}
        <ReportSection title="5. Detection Evidence">
          {data.evidence?.length > 0 ? (
            <EvidenceList records={data.evidence} />
          ) : (
            <p className="italic text-raven-text-tertiary">No evidence submitted.</p>
          )}
        </ReportSection>

        {/* 6. Attack Reconstruction */}
        <ReportSection title="6. Attack Reconstruction">
          {data.reconstruction?.stages ? (
            <div className="pl-4">
              {data.reconstruction.stages.map((stage: any, idx: number) => (
                <AttackStageCard 
                  key={stage.id} 
                  stage={stage} 
                  isLast={idx === data.reconstruction.stages.length - 1} 
                />
              ))}
            </div>
          ) : (
            <p className="italic text-raven-text-tertiary">Reconstruction pending.</p>
          )}
        </ReportSection>

        {/* 7. Impact */}
        <ReportSection title="7. Impact">
          {data.impact ? (
            <div className="space-y-6">
              <ImpactScore score={data.impact.demonstrationScore} severity={data.impact.overallSeverity} />
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {data.impact.categories.map((cat: any, idx: number) => (
                  <ImpactCategoryCard key={idx} data={cat} />
                ))}
              </div>
            </div>
          ) : (
            <p className="italic text-raven-text-tertiary">Impact assessment pending.</p>
          )}
        </ReportSection>

        {/* 8. Supporting Evidence */}
        <ReportSection title="8. Supporting Evidence">
           <p className="leading-relaxed mb-4">
            The findings in this report are corroborated by the following raw telemetry and forensic artifacts:
          </p>
          {data.evidence?.length > 0 ? (
            <EvidenceList records={data.evidence} />
          ) : (
            <p className="italic text-raven-text-tertiary">No supporting artifacts available.</p>
          )}
        </ReportSection>

        {/* 9. RARF Representation */}
        <ReportSection title="9. RARF Representation">
          {data.rarf ? (
            <RARFViewer document={data.rarf} />
          ) : (
            <p className="italic text-raven-text-tertiary">No Risk & Response Framework output available.</p>
          )}
        </ReportSection>

      </div>
    </div>
  );
}
